version: '3.8'

services:
  app: 
    container_name: fast-isignature.com
    build: 
      context: .
      dockerfile: Dockerfile
    tty: true
    working_dir: '/app'
    ports:
      - 3000:3000
      - 8000:8000
    volumes:
      - ./:/app
      - $HOME/.gitconfig:/home/node/.gitconfig
      - $HOME/.ssh:/home/node/.ssh